# Book settings
title: microfilm
#logo: 'logo.png'
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://github.com/guiwitz/microfilm

html:
  use_repository_button: true

sphinx:
  extra_extensions: [
  'sphinx.ext.autodoc',
  'sphinx.ext.napoleon'
  ]