name: microfilm
channels:
  - conda-forge
dependencies:
  - python>3.6
  - pandas
  - jupyter
  - jupyterlab
  - ipywidgets
  - pip
  - ipympl
  - pip:
    - tqdm
    - git+https://github.com/guiwitz/microfilm.git@master#egg=microfilm
