name: deploy-book

# Only run this manually
on: [workflow_dispatch]
  #push:
  #  branches:
  #  - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    # Install pip dependencies
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install -r book/requirements.txt
        $CONDA/bin/pip install .

    # Compile the docs
    - name: Compile sphinx
      run: |
        $CONDA/bin/sphinx-apidoc -o docs/source microfilm/

    # Build the book
    - name: Build the book
      run: |
        $CONDA/bin/jupyter-book build .
    
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
