name: tests

on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file binder/environment.yml --name base
    - name: Show versions
      run: |
        $CONDA/bin/conda list
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
